INSERT INTO organisasi (nama_ketua, bidang_keahlian, alamat, nomor_telepon) VALUES
                                                                                ('FARIES NAFISA NUSANTORO', 'SANGGAR SENI KERONCONG RINDU MALAM', 'Jl.Kyai Mojo Gg.Laos No.6 Kelurahan Ketanggi Kecamatan Ngawi   Kabupaten Ngawi', '6285640482938'),
                                                                                ('UMI USWAHTUN KHASANAH', 'SANGGAR SENI TARI', 'Sembung 02/04,Ds Sembung Kec.Karangjati', '6281335566656'),
                                                                                ('BOWO', 'OEMAH JOGLO NGAWI', 'Ds.Karang Tengah Kota, Ngawi', '62816567197'),
                                                                                ('BAMBANG TRIATMOKO', 'SANGGAR COKRO KEMBANG', 'Dsn.Kedungprahu, RT/RW: 003/001, Ds.widodaren, Kec.widodaren,Ngawi', '6281359406001'),
                                                                                ('IMAM JOKO SULISTYO', 'SANGGAR SENI "SOERYO BUDOYO"', 'Jln.Kartini No.30, Margomulyo Ngawi', '62816567867'),
                                                                                ('RUDIANTO', 'SANGGAR NGUJIWAT', 'Dsn.krajan RT/RW :12/01, Kedungputri, Paron', '6282139252326'),
                                                                                ('MUH RIYADUS SHOLIHIN', 'SANGGAR TARI PENTHUL MELIKAN 1952', 'MELIKAN, DS. PARON, KEC. PARON', '6281459111828'),
                                                                                ('ADI', 'SANGGAR WAYANG  KUKILO LARAS', 'Dsn. Mugu Raya, Ds.Kedungprahu, RT.004/RW.003, Kec.Padas, Kab.Ngawi', '628210362929'),
                                                                                ('EDI DARSONO', 'WAYANG KULIT SANGGAR " MADUKORO"', 'sambirobyong RT.06/05 , Klitik, Geneng', '6285648564883'),
                                                                                ('SUKADI', 'KERAWITAN', 'Ds.Mojo, Bringin', '6281235330933'),
                                                                                ('EKO WIDODO', 'WAYANG KULIT BODRONOYO', 'Ds.Kedungputri, Paron', '6281554221252'),
                                                                                ('AGUS TUSADJI', 'Ketoprak Hasto Budoyo', 'Desa Sidomakmur Widodaren', NULL),
                                                                                ('KARYANI/ARIES', 'PEDALANGAN  (PEPADI)', 'Ds.SIDOREJO,GENENG NGAWI/ DESA SUKOWIYONO II, PADAS NGAWI', '62853303376'),
                                                                                ('SASMITHO', 'SANGGAR SENI SRB LOHANSUNG', 'R.M LOHANSUNG 2, JL.RAYA JOGOROGO-NGRAMBE Ds.SETONO', '6285648840080'),
                                                                                ('ANIK PURWATI', 'SANGGAR SENI "NIKNOK BUDOYO"', 'Dsn.Lahar, Ds.Krompol RT/RW: 02/07, Kec.Bringin Kab.Ngawi', '6285655759015'),
                                                                                ('BIMO MAHARANI', 'SANGGAR ROCKET SMPN 2 KARANGJATI', 'SMP N 2 Karangjati , Kab.Ngawi', '62821 3880 5346 '),
                                                                                ('DARTO', 'SANGGAR SURODADHU', 'Desa Jambangan Paron Ngawi', '62856 4575 2493'),
                                                                                ('SUNGKONO', 'SANGGAR MAHEROKOCO', 'Desa Tempuran , Kecamatan Paron Kab.Ngawi', '62856 9188 2625'),
                                                                                ('SUPRIYADI', 'SANGGAR CENGKIR GADHING,', 'SDN Pangkur 1 , Kec.Pangkur, Kab.Ngawi', '62812 5961 7917'),
                                                                                ('MULYO SRI KRESNO', 'SANGGAR COKRO WATI', NULL, '62813 3580 5607'),
                                                                                ('HARTONI', 'SANGGAR MUSTIKA TANJUNG', 'Desa Tanjungsari Kec.Jogorogo Kab.Ngawi', '62812 5964 2527'),
                                                                                ('SULASNO', 'SANGGAR MASTUTI BUDAYA, DESA MOJO', 'Desa Mojo Kec.Bringin Kab.Ngawi', '62852 1727 2973'),
                                                                                ('AGUNG SRI KRESNO', 'SANGGAR KRESNO MUKTI', 'Desa Mantingan Kec.Mantingan', '6285728889689'),
                                                                                ('SARDI', 'SANGGAR KLANTHUNG JOMBLANG SALAK', 'Dsn. Jomblang Salak, Desa Pakah RT/RW: 01/03, Kec.Mantingan Kab.Ngawi', '6285732558734'),
                                                                                ('BONERAN', 'REOG SINGO MUDO MBANGAN', 'DUSUN KRAJAN 1 RT/RW: 23/01 KEDUNGPUTRI ,PARON', NULL),
                                                                                ('BAYU RISKA HAJI KOIRUL', 'REOG SIMO MUDO TERATE', 'TEMPEL, RT/RW: 4/3, TEGUHAN , PARON', NULL),
                                                                                ('HARNO', 'SINGO MUDO BIROWO', 'NNGESREP, RT/RW: 04/02, PARAS , PANGKUR, NGAWI', NULL),
                                                                                ('EKO SUPRAYITNO', 'REOG SINGO WAHYU BUDOYO', 'JL.MANYAR, RT/RW: 06/02, DESA BERAN NGAWI', '6285733768908'),
                                                                                ('MARGONO', 'REOG DAN JARANAN BOLO SINGO NGAWI', 'KARANGJATI, RT/RW: 04/01 DESA KARANGJATI NGAWI', NULL),
                                                                                ('RUDI SUSANTO', 'REOG GEMBONG SINGO SATRIO', 'PAKIS, RT/RW: 01/01, NGROMPOL BRINGIN', NULL),
                                                                                ('SIPAN', 'REOG SINGO JATI MULYO', 'CUNG BELUT, RT/RW: 7/2, SEMEN PARON', NULL),
                                                                                ('RIYANTO', 'JARANAN SATRIYO TRUNOJOYO', 'CANGAKAN II, RT/RW:03/03, CANGAKAN KASREMAN', NULL),
                                                                                ('MOHAMMAD ARYOS RAMADHAN', 'REOG SARDULO TAMTAMA AJI', 'JL.KYAI MOJO GG.II, RT/RW:5/1 , PELEM NGAWI', NULL),
                                                                                ('SUGIYANTO', 'REOG MINUK LEGO BUDOYO', 'KITERAN, RT/RW: 04/03, LEGOWETAN BRINGIN, NGAWI', NULL),
                                                                                ('ARI YUNIANTO', 'REOG SINGO TARUNO BUDOYO,', 'SAMBIROBYONG, RT/RW: 2/7, GENENG NGAWI', '6285713839979'),
                                                                                ('DWI HENDRA BAYU SULISTYONO', 'REOG DAN JARAN SINGO MUDHO ONTOSENO', 'BABADAN WETAN ,PARON , NGAWI', '6281548607829'),
                                                                                ('SUSANTO', 'REOG SINGO ROGO JOYO', 'KEDUNGREJO,RT/RW: 3/4, DESA KLITIK GENENG', '6285259906712'),
                                                                                ('SUPARDI', 'REOG SINGO LANGU JOGOROGO', 'BALEPANJANG, JOGOROGO, NGAWI', '6281556780633'),
                                                                                ('DIDIK SUGIYANTO', 'REOG SARDULO TAMBAK SELO PUTRO', 'PLANG LOR, RT/RW:02/01, KEDUNGGALAR, NGAWI', '6285708018778'),
                                                                                ('HARI PRAYITNO', 'REOG SINGO PRAYITNO BUDOYO', 'KEDUNGGALAR, RT/RW:3/8, KEDUNGGALAR, NGAWI', NULL),
                                                                                ('HERI SUPARDI', 'REOG MARGO SINGO MENGGOLO', 'PLAMPON, GENENG, NGAWI', NULL),
                                                                                ('SUPARDI', 'JARANAN TURONGGO NYAMPLUNG JOYO MULYO', 'KENONGOREJO, RT/RW: 1/3,BRINGIN, NGAWI', '6285855018559'),
                                                                                ('BAYU', 'JARANAN SINGO MUDO BIROWO', 'PARAS RT/RW: 4/2, PANGKUR, NGAWI', '6281225484394'),
                                                                                ('TEGAR BUYUNG ROMADHON', 'REOGB DAN JARANAN NEW BEDIGAS LARAS', 'GERBANG SEWU, SEMEN PARON', '6285807250879'),
                                                                                ('HERY SUSANTO', 'REOG SINGO MANUNGGAL', 'KETANGGI,KARTOHARJO, NGAWI', '628125974670'),
                                                                                ('JOKO SUWARNO', 'REOG SINGO JATI MULYO', 'SEMEN, RT/RW: 01/01, SEMEN PARON', '6285732767822'),
                                                                                ('DIANDOKO', 'REOG SINGO KRIDO MANUNGGAL', 'JENANGAN II, RT/RW:7/2, JENANGAN, KWADUNGAN', '6285624444088'),
                                                                                ('EKO CAHYONO', 'REOG SINGO TRUNOJOYO', 'SAMBIROBYONG, DESA GENENG, GENENG, NGAWI', NULL),
                                                                                ('GRENDI PIONERESIAN', 'REOG SISWO SARDULO SETO', 'JL.TRUNOJOYO GG.II, RT/RW:11/5, KARANGTENGAH, NGAWI', '6285804050500'),
                                                                                ('JONI ISKANDAr', 'ORKES SAFIRA', 'Dsn.TEPAS II, RT/RW: 04/04, TEPAS, GENENG', NULL),
                                                                                ('SARTOYO', 'ORKES NEW ALIZHA', 'Dsn.NONGO, RT/RW: 02/02, KENONGOREJO, BRINGIN', '6282231922878'),
                                                                                ('PUMA SETYAWAN', 'ORKES R NADA', 'NGANDONG, RT/RW: 01/10, KARANGTENGAH PRANDON, NGAWI', NULL),
                                                                                ('DIDIN SAHRUL MUHTAKHIN', 'ORKES EMERALD', 'DSN. KARASAN, DS. WAROK TENGAH, KEC. PANGKUR, KAB. NGAWI', NULL),
                                                                                ('DA IMIL KHASANAH', 'ORKES BHARATA GREESS', 'DSN. SUKOWIYONO, DS. SUKOWIYONO, RT/RW. 001/004, KEC. PADAS, KAB NGAWI', NULL),
                                                                                ('HARJUNANTO BUDI PRASETYA', 'ORKES OM DEVITA', 'BRANGOL, RT/RW. 04/02, KARANGJATI, NGAWI', '6281233261169'),
                                                                                ('AJIS SAPUTRA', 'ORKES OM ZENETA', 'DS. KEDUNGGALAH, RT/RW. 03/05, KEC. GENENG, KAB. NGAWI', '6281229122993'),
                                                                                ('YOCKI ERSANA', 'GROUP KOLINTANG SRIKANDI NGAWI RAMAH', 'DS. KLITIK, RT/RW. 01/04, KEC. GENENG, KAB. NGAWI', NULL),
                                                                                ('BEKTI PRASETYA', 'ORKES TARANTULA MUSIK', 'DS. GUYUNG, DS. GUYUNG, RT/RW. 03/02, KEC. GERIH, KAB. NGAWI', '6281233183357'),
                                                                                ('NURIYANTO', 'PAGUYUBAN WAYANG ORANG KAKUNG SEMAWI', 'DSN. BAYEMKALANG I, RT/RW. 03/03, DS. KERASWETAN, KEC. GENENG, KAB. NGAWI', '6285334900464'),
                                                                                ('SUMADI', 'KETOPRAK MADYO BUDOYO', 'DS. TEGUHAN, KEC. PARON, KAB. NGAWI', NULL),
                                                                                ('HJ. SRI WIDAJATI M.SI', 'KETOPRAK SRI BUDAYA', 'DS. JERUREJO, KEC. NGAWI, KAB. NGAWI', NULL),
                                                                                ('KHOIRUL IHSAN', 'KARAWITAN MANUNGGAL LARAS', 'DSN. TAPEN, DS. TAPEN, RT/RW. 06/02, KEC. PANGKUR, KAB. NGAWI', '62813344054381'),
                                                                                ('SRIYONO', 'KARAWITAN TRISNO BUDOYO', 'DSN. MOJOMANIS, DS. MOJOMANIS, KEC. KWADUNGAN, KAB. NGAWI', 85607539247),
                                                                                ('DIDIN SAHRUL MUHTAKHIN', 'KARAWITAN ARUM LARAS', 'DSN. KARASAN, DS. WAROK TENGAH, KEC. PANGKUR, KAB. NGAWI', NULL),
                                                                                ('SUKAMTO ,S.P', 'KARAWITAN LESTARI BUDAYA', 'DS. DANGUK, KEC. KARANGJATI, KAB. NGAWI', NULL),
                                                                                ('SUTOKO', 'KARAWITAN NGUDYO LARAS', 'DSN. BARENG, DS. KENONGOREJO, RT/RW. 02/05, KEC. BRINGIN, KAB. NGAWI', NULL),
                                                                                ('SUWARNO', 'KARAWITAN MADYO LARAS', 'DSN. SIDOMULYO, DS. KENITEN, RT/RW. 02/05, KEC. GENENG, KAB. NGAWI', NULL),
                                                                                ('RUDIANTO', 'KARAWITAN REMAJA NEW BEDIGAS LARAS', 'DSN. KRAJAN, DS. KEDUNG PUTRI, RT/RW. 13/01, KEC PARON, KAB. NGAWI', NULL),
                                                                                ('WARSONO', 'KARAWITAN MARSUDI BUDAYA', 'DS. MOJO, RT/RW. 03/04, KEC. BRINGIN, KAB. NGAWI', NULL),
                                                                                ('AGUS HARTOYO', 'KARAWITAN NGUDI BUDOYO LARAS', 'DS. BADERAH, RT/RW. 06/02, KEC. GENENG, KAB. NGAWI', NULL),
                                                                                ('SUTRISNO', 'KARAWITAN TRESNO LARAS', 'DS. JATIMULYO, KEC. MANTINGAN, KAB. NGAWI', '6285852402915'),
                                                                                ('GANDI', 'KARAWITAN JATI LARAS', 'DS. KARANGTENGAH PRANDON, RT/RW. 01/12, KEC. NGAWI, KAB. NGAWI', NULL),
                                                                                ('JUWARI', 'KARAWITAN MUDHO IROMO', 'DS. DAMPT, KEC. BRINGIN, KAB. NGAWI', '6282299972202'),
                                                                                ('SUDARNO', 'KARAWITAN SLENK GROUP', 'DSN. SIWALAN, DS. WIDODAREN, RT/RW. 03/03, KEC. GERIH, KAB. NGAWI', '62853815829700'),
                                                                                ('SURAHMAN', 'KARAWITAN OERIP BUDAYA', 'JL. BRANJANGAN, RT/RW. 03/01, KEC. NGAWI, KAB. NGAWI', '6281335796465'),
                                                                                ('PANDI', 'KARAWITAN RUKUN BUDAYA', 'DS. KWADUNGAN LOR, KEC. PADAS, KAB NGAWI', '6281359210128'),
                                                                                ('SUPARNI', 'KARAWITAN SIDO MUNCUL', 'DSN. GODANG, DS. REJOMULYO, RT/RW. 08/02, KEC. KARANGJATI, KAB. NGAWI', '6281252476659'),
                                                                                ('DARMAJI', 'ELEKTON ANDARA', 'DS. BANJARBANGI, KEC. PITU, KAB. NGAWI', NULL),
                                                                                ('NURSILO', 'CAMPURSARI MBANGUN LARAS', 'DSN. GAMBANG, DS. GIRIMULYO, RT/RW. 05/04, KEC. JOGOROGO, KAB. NGAWI', '6281335799854'),
                                                                                ('SUYADI PRASETYO', 'ELEKTON LOKANANTA', 'DS. KARANGBANYU, KEC. WIDODAREN, KAB. NGAWI', NULL),
                                                                                ('PARMIN', 'CAMPURSARI ROMO WILIZ', 'DSN. TAKTENG, DS. BANGUNREJO, RT/RW. 02/04, KEC. KARANGANYAR', '6282230409042'),
                                                                                ('ICUN APRIN DEBY PALUPI', 'ELEKTON ICUN PRODUCTION', 'DSN. SAMBEN 2, RT/RW. 03/03, DS. SIDOKERTO, KEC. KARANGJATI, KAB. NGAWI', '6281803317416'),
                                                                                ('BINTANG NUSANTARA ,AMD.SN', 'CAMPURSARI GANDRUNG LARAS', 'DSN. KRAJAN, RT/RW. 01/02, DS. KUNIRAN, KEC. SINE, KAB. NGAWI', '6282123504224'),
                                                                                ('IRON RIVA''I', 'ELEKTON SUMBER RIZQI ENTERTAINMENT', 'DSN. GERIH, DS. GERIH, RT/RW. 08/01, KEC. GERIH, KAB. NGAWI', '6281217196008'),
                                                                                ('DARSI', 'ELEKTON BUNDAKU', 'DSN. CENGKLIK, DS. BANGUNREJO, RT/RW. 04/02, KEC. PITU, KAB. NGAWI', NULL),
                                                                                ('GUNAWAN', 'CAMPURSARI PUTRA BUDAYA', 'DSN. TRETES, DS. KARANGBANYU, RT/RW. 04/07, KEC. WIDODAREN, KAB. NGAWI', '6285235936164'),
                                                                                ('MUNASIR', 'CAMPURSARI PURNAMA', 'DSN. MBUGEL, DS. KARANGREJO, RT/RW. 05/04, KEC. KENDAL, KAB. NGAWI', '6285649959684'),
                                                                                ('SUWARTI', 'ELECTONE SEKAR GADUNG', 'DSN. GADUNG, DS. NGROMPO, RT/RW. 02/01, KEC. PANGKUR, KAB. NAWI', '6283845505799'),
                                                                                ('PUJIWANTO', 'ELEKTON NEW SEKARWANGI', 'DS. KLITIK, RT/RW. 05/03, KEC. GENENG, KAB. NGAWI', NULL),
                                                                                ('SUTEJO', 'CAMPURSARI BARASTA', 'DSN. KEDUNGPRAHU, DS. WIDODAREN, KEC. WIDODAREN, KAB. NGAWI', NULL),
                                                                                ('YOGA NIRBITA ILHAM', 'JUNIOR PRODUCTION', 'DS. GUYUNG, KEC. GERIH, KAB. NGAWI', NULL),
                                                                                ('SUTRISNO', 'CAMPURSARI DIYA RAMA', 'DS.  POJOK III, RT/RW. 01/03, KEC. KWADUNGAN, KAB. NGAWI', '6282232318867'),
                                                                                ('SUKADI', 'CAMPURSARI DEWANGGA', 'WATUALANG, NGAWI', NULL),
                                                                                ('SUGENG JATMIKO', 'CAMPURSARI GANDRUNG LARAS', 'KRAJAN,RT/RW: 01/02, KUNIRAN SINE, NGAWI', NULL),
                                                                                ('SUYANTO', 'CAMPURSARI DEWATA', 'NGELO,TR/RW:3/2, JATIMULYO, MANTINGAN, NGAWI', '6285235670233'),
                                                                                ('JOKO PURWANTO', 'CAMPURSARI ORLANDO', 'KRAJAN WETAN, RT/RW: 3/1, SINE, NGAWI', NULL),
                                                                                ('SUDIRMAN', 'CAMPURSARI SURYA NADA', 'PELEM,NGAWI', '6285735659461'),
                                                                                ('RATNA DWI SUSILOWATI', 'ELECTONE JAVA ENTERTAINER', 'KENONGOREJO, RT/RW: 2/3,DADAPAN, KENDAL  NGAWI', '6285735380465'),
                                                                                ('SUWARNO', 'CAMPURSARI GAYENG ROSO', 'PANUKAN', '6285730744686'),
                                                                                ('SARJI', 'CAMPURSARI JOKO LOLA', 'SOCO, GONDANG LEGI, JOGOROGO', '6285843172725'),
                                                                                ('WIWIT RIYADI', 'CAMPURSARI ABDI ROSO', 'JL.PATIMURA, NGLARANGAN, NGAWI', '6285235000479'),
                                                                                ('NURSILO', 'CAMPURSARI BANGUN LARAS', 'GAMBANG, RT/RW: 06/04, GIRIMULYO , JOGOROGO', '6281335799854'),
                                                                                ('WISNU SRI GANDONO', 'CAMPURSARI YUNITA NADA', 'GUYUNG II,RT/RW:5/2, GUYUNG, GERIH, NGAWI', '6282338200809'),
                                                                                ('ENDANG DWI RUMANTI', 'CAMPURSARI MBOYAK', 'JL.SILIWANGI, NO.14, JRUBONG,NGAWI KAB.NGAWI', '628125981453'),
                                                                                ('AHMAD NUR KHOLIS', 'CAMPURSARI SANTIKA', 'DS.JATEN, RT/RW:01/01, JOOROGO, KAB.NGAWI', '6281285681303'),
                                                                                ('KARYANI', 'CAMPURSARI ABDI SENI', 'DS.SIDOREJO, RT/RW:4/1, KEC.GENENG, KAB.NGAWI', '6285330337600'),
                                                                                ('MARNO BOWIE RUDIONO', 'CAMPURSARI VANEYSA NADA', 'GERIH, RT/RW:7/2, KEC.GERIH, KAB.NGAWI', '6285746123200'),
                                                                                ('LAILATUL QODRIYATI KINASIH', 'HADROH MODERN ALFATIH', 'JL. Barnadip No. 18, RT.008/RW.004, Margomulyo, Kec. Ngawi, Kab. Ngawi', '6281217006010'),
                                                                                ('TRI PUJO PRASETYO', 'ELECTONE" MAHADEWA"', 'Ds. Kwadungan Lor, RT.003/RW.002, Kec. Padas, Kab. Ngawi', '6285807234424'),
                                                                                ('SUYANTO', 'ELECTONE MANUNGGAL LARAS', 'Dongol II, RT.004/RW.009, Ds. Klampisan, Kec. Geneng, Kab. Ngawi', '6282337848265'),
                                                                                ('RUDI HANDOYO', 'CAMPURSARI GROP PERMATA MUSIK', 'Dsn. Jaten, RT.003/RW.001, Ds. Jaten, Kec. Jogorogo, Kab. Ngawi', '6281556787992'),
                                                                                ('BUDI SANTOSO', 'KARAWITAN SRI KENCONO LARAS', 'Dongol I, RT.006/RW.006, Ds. Klampisan, Kec. Geneng, Kab. Ngawi', '6285203349066'),
                                                                                ('SULARSO', 'KETOPRAK MUKTI WIBOWO', 'Desa Planglor Kedunggalar', NULL),
                                                                                ('SUWARTI', 'ORKES YEZZ YOU KERONCONG KOMUNITAS', 'Ploso Rejo, RT.007/RW.006, Ds. Kedunggalar, Kec. Kedunggalar, Kab Ngawi', '6281233196668'),
                                                                                ('ALI SUJITO', 'REOG SASANA SEMUT IRENG PSHT RAYON REJUNO', 'Rejuno, RT.006/RW.001, Ds. Rejuno, Kec. Karangjati, Kab. Ngawi', '6282210988431'),
                                                                                ('SUTARYONO', 'KARAWITAN HANGESTI LARAS', 'Dsn. Gempol, RT.002/RW.006, Ds. Gempol, Kec. Karangjati, Kab. Ngawi', '6285204388130'),
                                                                                ('SUJIMIN', 'KARAWITAN LEGO SWORO', 'Dsn. Kedungwaluh, RT.002/RW.002, Ds. Campurasri, Kec. Karangjati, Kab. Ngawi', '6285790357200'),
                                                                                ('SUMIATI', 'COKEKAN MAJU LANCAR', 'Dsn. Gulingan, RT.001/RW.005, Ds. Widodaren, Kec. Gerih, Kab. Ngawi', '6282335866061'),
                                                                                ('HARIYONO', 'CAMPURSARI NEW RAMA MUSICA', 'Dsn. Gedong, Ds. Kendung III, RT.002/RW.003, Kec. Kwadungan, Kab. Ngawi', '6285330537209'),
                                                                                ('JOKO SUWARNO', 'REOG SINGO JATI MULYO', 'Dsn. Cungbelut, Ds. Semen RT.001/RW.011, Kec. Paron Kab. Ngawi', '6285732767822'),
                                                                                ('TEGAR BUYUNG ROMADHON', 'KARAWITAN NEW BEDIGAS LARAS', 'Dsn. Gebang Sewu, Ds. Semen RT. 003/RW. 015, Kec. Paron, Kab. Ngawi', '6285267208657'),
                                                                                ('TEGAR BUYUNG ROMADHON', 'REOG NEW BEDIGAS LARAS', 'Dsn. Gebang Sewu, Ds. Semen RT. 003/RW. 015, Kec. Paron, Kab. Ngawi', '6285267208657'),
                                                                                ('TRI MARSAHID', 'CAMPURSARI PANDAWA MUSIK', 'Dsn. Teluk, Ds. Sambirejo, RT. 003 / RW. 003, Kec. Mantingan, Kab. Ngawi', '6285229658543'),
                                                                                ('GUNARTO, S.Sn, M.Sn.', 'KOMUNITAS OMAH SENI KREATIF', 'Desa Kuniran Sine', NULL),
                                                                                ('JOKO SANTOSO', 'ORKES REVISKA MUSIC', 'Dsn. Cumpleng, Ds. Gandong, RT. 005/RW.002, Kec. Bringin, Kab. Ngawi', '6281331690006'),
                                                                                ('HIMAWAN PAMUJI', 'ELEKTONE RAFA MUSIC', 'Dsn.Puhti, RT/RW : 007/001, Desa Puhti, Kec.Karangjati, Kab. Ngawi', '6281803448279'),
                                                                                ('SUTRISNO', 'CAMPURSARI DIVA RAMA', 'Dsn. Pojok III, Ds. Pojok, RT.001/RW.003, Kec. Kwadungan, Kab. Ngawi', '6282232318867'),
                                                                                ('ADI FIRNANDA', 'CAMPURSARI SURYA NADA', 'Dsn.Pelem, Ds. Pelem, RT.007/RW.002, Kec. Ngawi, Kab.Ngawi', '6285850502711'),
                                                                                ('RUSMANTO', 'CAMPURSARI HAPSARI', 'Dsn.Ngrendeng, Ds. Ngrendeng, RT.004/RW.001, Kec. Sine, Kab.Ngawi', '6281331220559'),
                                                                                ('SLAMET', 'KETOPRAK DHONGKOL BOEDHOYO', 'Desa Kebon RT.01/RW.13, Kec.Paron, Kab.Ngawi', '6282230765000'),
                                                                                ('DIANDOKO', 'REOG SINGO0 KRIDO MANUNGGAL', 'Dsn Jenangan RT/RW: 07/02, Desa Jenangan Kec.Kwadungan Kab.Ngawi', '6285624444088'),
                                                                                ('EKO ADI PRAYITNO', 'CAMPURSARI EKO NADA', 'Gilis Desa Ploso, RT/RW: 04/01, Kecamatan Kendal, Kab.Ngawi', '6282228768004'),
                                                                                ('BAGUS RIZKI TRI SAPUTRA', 'KARAWITAN BC.LARAS', 'PARAS , RT/RW: 02/01,  KEC. PANGKUR, KAB. NGAWI', '6285749031355'),
                                                                                ('SAMSURI', 'KARAWITAN TARUNO LARAS', 'DSN. GEMPOL, RT/RW. 001/002 DESA. GEMPOL, KEC, KARANGJATI, KAB. NGAWI', '6281233368255'),
                                                                                ('WAGIMIN', 'ELEKTONE WAGA ELECTONE', 'DSN. BALONG, RT/RW. 02/02, DESA. BERAN, KEC. NGAWI, KAB. NGAWI', '6285735445228'),
                                                                                ('HERU BAGUS PRASETIO', 'ELEKTONE CINTA NADA', 'DSN. KLIYANGAN,RT/RW.02/03,DESA. KAWU, KEC. KEDUNGGALAR, KAB. NGAWI', '6281553773931'),
                                                                                ('TOYINAH', 'SANGGAR TARI SRIKANDI', 'Desa Ngale Paron', NULL),
                                                                                ('WASIS DARMONO', 'ELEKTONE MUSTIKO LARAS', 'CENGKLIK RT/RW: 01/02, BANGUN REJO LOR, PITU', '6285330746586'),
                                                                                ('PUGUH HIDAYAT', 'ORKES KUKILO LARAS', 'DSN.SAMBIROTO, DS.SAMBIROTO RT/RW: 02/02,  KEC.PADAS KAB.NGAWI', '6285210362929'),
                                                                                ('SUPARDI', 'CAMPURSARI KIDUNG PANJALU', 'DSN.KRAJAN, DS.KUNIRAN RT/RW: 03/02,  KEC.SINE KAB. NGAWI', '6282257679584'),
                                                                                ('IMAM FUJIANTO', 'CAMPURSARI ARDUTT MUSIK', 'DS.MUNGGUT RT/RW: 04/03,  KEC.PADAS,  KAB. NGAWI', '6285784694373'),
                                                                                ('DWI YANTO', 'ORKES  AREGHA MUSIC', 'DSN. REJUNO, DS.REJUNO N, RT/RW: 005/001, KEC. KARANGJATI, KAB. NGAWI', '6285855017921'),
                                                                                ('ARIS EKA SAPUTRA', 'ORKES  MALIKA MUSIC', 'DSN.KUMPULREJO, DS.SUMBER BENING RT/RW: 15/05,  KEC.BRINGIN KAB. NGAWI', '6285648728253'),
                                                                                ('HENDRA SAPUTRA', 'ELEKTONE HS. MUSIC', 'DS.KARANGJATI RT/RW: 05/01,  KEC.KARANGJATI  KAB. NGAWI', '6287865043661'),
                                                                                ('DIDIK MARIANTO', 'ELEKTONE RENJANA', 'DSN. NGEMBAK, DS.MUNGGUT, RT/RW: 002/004, KEC. PADAS, KAB. NGAWI', '6285790655571'),
                                                                                ('SUWARNO', 'KARAWITAN EKA LANGGENG BUDAYA', 'Desa  Gemarang Kec.Kedunggalar', NULL),
                                                                                ('Pradana Dykdhya Wahana )', 'KARAWITAN MUDO IROMO', 'Desa Setono Kec. Ngrambe', '6285233042487'),
                                                                                ('Tomi Giatno L', 'PAGUYUPAN SENI BUDAYA TRADISI KETOPRAK PUSPA BUDAYA', 'Kelurahan Pelem Kec. Ngawi', '6281249977979'),
                                                                                ('Fauzan Putra Ardyansyah', 'REOG SARDULO SETO MENGOLO', 'Desa Walikukun Kec. Widodaren', '6285733290360'),
                                                                                ('Soeradji', 'SANGGAR SENI GLAGAH WANGI', 'Desa Semen Kec.Paron', '628123428197'),
                                                                                ('TITIS INTAN TIYAS', 'SANGGAR HASTA BUDAYA SCHOOL', 'Desa Gendingan Widodaren', '6287861331039'),
                                                                                ('MUH RIYADUS SHOLIHIN', 'SANGGAR SENI PENTHUL MELIKAN', 'Dsn. Melikan, Ds. Tempuran, Kec. Paron, Kab. Ngawi', '6281459111828'),
                                                                                ('Kartiningsih', 'SANGGAR TARI', 'Jogorogo, RT.004/RW.007, Kec. Jogorogo, Kab. Ngawi', '6281216351573'),
                                                                                ('Kardi', 'KARAWITAN AMONG ROSO', 'Dsn. Kaliwangon, RT.006/RW.003, Ds. Dero, Kec. Bringin, Kab. Ngawi', '6285649207546'),
                                                                                ('Saidi', 'KETOPRAK', 'Dsn. Sidorejo, RT.007/RW.005, Ds. Gentong, Kec. Paron, Kab. Ngawi', NULL),
                                                                                ('Sugiarto', 'CAMPURSARI', 'Dsn. Suruh, Ds. Suruh, RT .010/RW ,004, Kec. Bringin, Kab. Ngawi', '6281232050935'),
                                                                                ('BENTUNG ARIF BINTORO', 'CAMPURSARI "SABDO MANGGOLO"', 'Dsn. Krajan, Ds. Kedungputri, RT. 003/RW.001, Kec. Paron, Kab. Ngawi', '6285853640635'),
                                                                                ('BENTUNG ARIF BINTORO', 'REOG " SINGO SABDO MANGGOLO"', 'Dsn. Krajan, Ds. Kedungputri, RT. 003/RW.001, Kec. Paron, Kab. Ngawi', '6285853640635'),
                                                                                ('Hj. SRI WIDAJATI S.Pd.M.Si', 'SANGGAR SENI', 'JL. MT. Haryono NO.6, Ds. Jururejo, RT.002/RW.010, Kec. Ngawi, Kab. Ngawi', '6282333900944'),
                                                                                ('Bambang Irawan', 'KARAWITAN', 'Dsn. Plosorejo, Ds. Kandangan, RT.004/RW.009, Kec. Ngawi, Kab. Ngawi', '6282312146415'),
                                                                                ('Bambang Irawan', 'JARANAN', 'Dsn. Plosorejo, Ds. Kandangan, RT.004/RW.009, Kec. Ngawi, Kab. Ngawi', '6282312146415'),
                                                                                ('RUSMIHARJO', 'GEMBRUNG', 'Dsn. Puhti, Ds.Puhti, RT.003/RW.002, Kec. Karangjati, Kab.Ngawi', '6282132462977'),
                                                                                ('SOLIKIN', 'ORKES NEW CAKRA MUSIK', 'Dsn. Krawut, Ds. Mangunharjo, RT.003/RW.011, Kec. Ngawi, Kab. Ngawi', '6285733631748'),
                                                                                ('SOLIKIN', 'CAMPURSARI NEW CAKRA MUSIK', 'Dsn. Krawut, Ds. Mangunharjo, RT.003/RW.011, Kec. Ngawi, Kab. Ngawi', '6285733631748'),
                                                                                ('YANISTA SENIAWAN', 'ORKES', 'Dsn. Guyung ll, Dsn. Guyung, RT.008/RW.002, Kec. Gerih, Kab. Ngawi', '6281390074048'),
                                                                                ('JOKO ISKANDAR', 'ORKES SAFIRA', 'Dsn. Tepas II, RT.004/RW.004, Ds. Tepas, Kec. Geneng, Kab. Ngawi', '6285738853459'),
                                                                                ('DIDIN SAHRUL MUTHAKIN', 'KARAWITAN', 'Dsn. Karasan, Ds. Waruk Tengah, RT.002/RW.003,Kec. Pangkur, Kab. Ngawi', '6285649367602'),
                                                                                ('MASIRUN', 'REOG', 'DSN. Wadangkerep, Ds. SEKARALAS, RT/RW. 001/002, Kec. Widodaren, Kab. Ngawi', '6285476630620'),
                                                                                ('SUGIONO', 'REOG', 'Dsn.Jaduk, Ds. Kedungputri, RT.005/RW.001, Kec. Paron, Kab. Ngawi', '6281803185530'),
                                                                                ('ARGO CATUR YUWONO', 'REOG/JARANAN SINGO MUDO PANDOWO', 'GUYUNG RT/RW: 4/1, GUYUNG GERIG', NULL),
                                                                                ('SRIYONO', 'ORKES', 'Dsn.Widodaren, Ds.Widodaren, Rt.005/Rw.002, Kec.Gerih, Kab.NGAWI', '6285853636279'),
                                                                                ('DIAN HADI SULISTIYO', 'ELEKTONE DIRA MUSICA', 'JL.Yos Sudarso Gg.Indra Giri RT/RW: 02/01 Kel.Margomulyo, Ngawi', '6281231723757'),
                                                                                ('SARBUDI', 'COKEKAN SARTO BUDOYO', 'Ngepeh Ds.Gandri  RT/RW: 02/04 Kec.Pangkur Kab.Ngawi', '6281335829642'),
                                                                                ('ARI WAHYU KURNIAWAN', 'KARAWITAN / CAMPURSARI "MUDHO LARAS ORIGINAL"', 'Manggong Ds.Paras RT/RW: 1/3, Kec. Pangkur  Kab. Ngawi', NULL),
                                                                                ('BAYU RIYANTO', 'CAMPURSARI', 'Dempel 2, Desa Dempel, RT/RW: 01/02, Kec. Geneng Kab. Ngawi', '6285649224229'),
                                                                                ('BAYU RIYANTO', 'ORKES', 'Dempel 2, Desa Dempel, RT/RW: 01/02, Kec. Geneng Kab. Ngawi', '6285649224229'),
                                                                                ('WAHYU NURCHOLIS', 'ORKES', 'DS.SIDOREJO   KEC. KARANGJATI , KAB. NGAWI', NULL),
                                                                                ('SAMSUL ARIFIN', 'ELEKTONE', 'DSN. NGEMBAK, DS.MUNGGUT, RT/RW: 002/005, KEC. PADAS, KAB. NGAWI', '6285784694373'),
                                                                                ('SUTOPO', 'KARAWITAN', 'DSN. SEDONOREJO, RT/RW. 003/001, DS.WONOSARI, KEC. SINE, KAB. NGAWI', '6285601761534'),
                                                                                ('RAJIYO', 'KARAWITAN', 'Dsn.Tambakromo 04/01,Ds.Tambakromo Kec.Padas', NULL),
                                                                                ('ERIK SETIYAWAN', 'CAMPURSARI', 'DSN. SEDRAN, RT/RW. 003/001, DS.MANISHARJO, KEC. NGRAMBE, KAB. NGAWI', '6285335823712'),
                                                                                ('AGUS SUKARMAN', 'CAMPURSARI', 'BANDUNG, PARON, NGAWI', NULL),
                                                                                ('ANDIK SISWANTO', 'ORKES', 'DSN.GUYUNG, Ds. GUYUNG, RT.008/RW.002, Kec. Gerih, Kab.Ngawi', NULL),
                                                                                ('SUNYOTO', 'KARAWITAN', 'Gedangan, RT.04/RW.04, Kwadungan, Padas, Ngawi', NULL),
                                                                                ('Panca Agung Susilo', 'REOG', 'DSN. NGISOR, RT/RW. 017/002, DS.KEDUNGPUTRI, KEC.PARON, KAB.NGAWI', '6285856362101'),
                                                                                ('ANIK PURWATI', 'ELEKTON', 'DSN.LAHAR, DS.KROMPOL, RT/RW,02/07, KEC.BRINGIN, KAB.NGAWI', '6285655759015'),
                                                                                ('MOHAMMAD FACHRUDIN', 'SANGGAR GALERY TOSAN AJI', 'MUNGGUR, RT/RW, 003/002, DESA.GAYAM, KEC.KENDAL, KAB.NGAWI', '6285642697269'),
                                                                                ('DENNY APRIYANTO', 'SANGGAR SENI PADEPOKAN SENI MANUNGGAL NYAWIJI', 'DS PARON, RT/RW: 006/001 KEC. PARON, KAB. NGAWI', '6285856544944'),
                                                                                ('LUNTORO', 'SANGGAR SENI "PERMADANI"', 'DSN. BANJAR, RT/RW: 007/003 KEC. KASREMAN, KAB. NGAWI', '6285732365369'),
                                                                                ('LUNTORO', 'PAGUYUBAN SENI "NGREKSA BUDAYA"', 'DSN. BANJAR, RT/RW: 007/003 KEC. KASREMAN, KAB. NGAWI', '6285732365369'),
                                                                                ('PONO', 'KARAWITAN "CUNDOKO LARAS"', 'DSN. BARON, DS. JATIPURO, RT/RW. 008/003, KEC. KARANGJATI, KAB. NGAWI', NULL),
                                                                                ('DYAH SOEGIHARTI', 'HARPI NGAWI', 'DSN. MBLIMBING, DS.DAWU RT/RW. 005/002 KEC.PARON, KAB. NGAWI', '6282190775107'),
                                                                                ('SUYONO', 'PAGUYUBAN KAWULA KARATON SURAKARTA "PAKASA"', 'PULE, RT/RW: 02/01, DS.MANTINGAN, KEC.MANTINGAN, KAB.NGAWI', '628112644633'),
                                                                                ('YOGA PRINGGO LAKSONO', 'SANGGAR SENI  “ SIGURU LUKITO (S3L)”', 'Dsn.SAMBI, RT/RW:02/03, Ds.SIMO KEC.KENDAL  KAB. NGAWI', NULL),
                                                                                ('MIFTAKHUL HUDA', 'SANGGAR SENI TARI “SRI KANDI”', 'PRAMESAN, RT/RW, 003/003, DS.NGALE, KEC.PARON, KAB.NGAWI', '6281335615373'),
                                                                                ('KARDI', 'KARAWITAN “GEMBRUNG IROMO', 'DS. KWADUNGAN LOR RT/RW: 05/03 KEC. PADAS KAB. NGAWI', '6282233652588'),
                                                                                ('BUDI WASKITO', 'ELEKTONE “BERLIAN NADA”', 'DSN.GEDANGAN, RT/RW: 002/003, DS. KWADUNGAN LOR, KEC.PADAS , KAB. NGAWI', '6282141586037'),
                                                                                ('SRI HARTINI', 'PAGUYUBAN SENI WATI KAB NGAWI "SARASWATI"', 'JOHO,RT/RW, 01/08, DS.KARANGTENGAH PRANDON KEC.NGAWI, KAB, NGAWI', '6285704958394'),
                                                                                ('SOLIKIN', 'CAMPURSARI " ROMANSA"', 'Dsn.PUNTUK, RT/RW: 03/04, Ds.SODOMAKMUR, Kec. WIDODAREN , KAB.NGAWI', '6281216537532'),
                                                                                ('BIBIT', 'KARAWITAN " MARDI GUNO MUDO BUDOYO"', 'Dsn.MUGU RAYA, RT/RW: 03/03, Ds.KEDUNGPRAHU, Kec. PADAS , KAB.NGAWI', '628123477060'),
                                                                                ('SRI HARTINI', 'PAGUYUBAN SENI WATI KAB NGAWI "SARASWATI"', 'JOHO,RT/RW, 01/08, DS.KARANGTENGAH PRANDON KEC.NGAWI, KAB, NGAWI', NULL),
                                                                                ('GANDI', 'KARAWITAN " JATI LARAS"', 'Dsn. Gandu, Dsn. Karangtengah Prandon, RT. 001/RW012, Kec. Ngawi, Kab. Ngawi', NULL),
                                                                                ('SIDI', 'CAMPUR SARI "SUKO NEDO"', 'PUCANG, RT/RW:03/09, TAWUN, KASREMAN, KAB.NGAWI', NULL),
                                                                                ('LUNTORO', 'PAGUYUBAN SENI "NGREKSA BUDAYA"', 'BANJAR,KIYONTEN, RT/RW: 07/03. KASREMAN, KAB. NGAWI', NULL),
                                                                                ('SUYONO', 'PAGUYUBAN KAWULA KARATON SURAKARTA "PAKASA"', 'PULE, RT/RW: 02/01, DS.MANTINGAN, KEC.MANTINGAN, KAB.NGAWI', NULL),
                                                                                ('JUWARI', 'KARAWITAN MUDHO IROMO', 'DS. DAMPIT KEC. BRINGIN KAB. NGAWI', NULL),
                                                                                ('YOGA PRINGGO LAKSONO', 'SANGGAR SENI  “ SIGURU LUKITO (S3L)”', 'Dsn.SAMBI, RT/RW:02/03, Ds.SIMO KEC.KENDAL  KAB. NGAWI', NULL),
                                                                                ('MIFTAKHUL HUDA', 'SANGGAR SENI TARI “SRI KANDI”', 'PRAMESAN, RT/RW, 003/003, DS.NGALE, KEC.PARON, KAB.NGAWI', NULL),
                                                                                ('KARDI', 'KARAWITAN “GEMBRUNG IROMO', 'DS. KWADUNGAN LOR RT/RW: 05/03 KEC. PADAS KAB. NGAWI', NULL),
                                                                                ('BUDI WASKITO', 'ELEKTONE “BERLIAN NADA”', 'DSN.GEDANGAN, RT/RW: 002/003, DS. KWADUNGAN LOR, KEC.PADAS , KAB. NGAWI', NULL),
                                                                                ('SOLIKIN', 'CAMPURSARI " ROMANSA"', 'Dsn.PUNTUK, RT/RW: 03/04, Ds.SODOMAKMUR, Kec. WIDODAREN , KAB.NGAWI', NULL),
                                                                                ('SOERADJI', 'SANGGAR SENI "GELAGAH WANGI"', 'DUSUN SEMEN, RT/RW: 001/008, DS.SEMEN, PARON, KAB.NGAWI', NULL),
                                                                                ('ARIS BUDI SANTOSO', 'PEPADI NGAWI', 'SUKOWIYONO II, RT/RW: 002/002, DS.SUKOWIYONO, KEC.PADAS, KAB.NGAWI', NULL),
                                                                                ('MARTONO', 'HADROH "EL ROSYIDA"', 'SURUH, RT/RW: 005/003, DS.SURUH, KEC.BRINGIN, KAB.NGAWI', NULL),
                                                                                ('MARGONO', 'REOG DAN JARANAN "BOLO SINGO NGAWI"', 'KARANGJATI RT/RW: 09/01. DESA KARANG JATI NGAWI', NULL),
                                                                                ('MARGONO', 'REOG  " SINGO KERTO NGGOLO"', 'KARANGJATI RT/RW: 09/01. DESA KARANG JATI NGAWI', NULL),
                                                                                ('SUDARSONO', 'CAMPURSARI " JP MUSIC"', 'NGILON RT/RW: 010/003, BANGUNREJO LOR ,KEC.PITU NGAWI', NULL),
                                                                                ('SYESAR ANDIK CAHYONO', 'CAMPURSARI " DIVA NADA"', 'KEDUNGGALAR,RT/RW: 003/003,KEDUNGGALAR, NGAWI', NULL),
                                                                                ('NANIK WINARTI', 'SANGGAR SENI SINGO MUDHO ORIGINAL (TMO)', 'CUNG BELUT,RT/RW: 004/012, SEMEN, PARON ,NGAWI', NULL),
                                                                                ('HERRY SUSANTO', 'REOG  " SINGO MANUNGGAL"', 'KETANGGI, DS.KARTOHARJO, RT/RW: 03/03 KEC.NGAWI, NGAWI', NULL),
                                                                                ('BAGAS WIBI HARIYANTO', 'CAMPURSARI "BOSS GENK"', 'BALEPANJANG,RT/RW:06/05, DS.JOGOROGO, KEC.JOGOROGO, NGAWI', NULL),
                                                                                ('SUKATMUN', 'KARAWITAN " MULYO BUDOYO"', 'KRAWUT.RT/RW:02/12, MANGUNHARJO, NGAWI, KAB.NGAWI', NULL),
                                                                                ('SUPRIYANTO', 'CAMPURSARI KLIWON NADA', 'Ds.KRAJAN, Ds.DAWUNG, RT/RW: 06/02, KEC.JOGOROGO, KAB.NGAWI', NULL),
                                                                                ('DIMAS YULIAN SYAHPUTRA', 'RAFFAZA MUSIC CAMPURSARI', 'TIRAK III, RT/RW: 01/03, KEC.KWADUNGAN, KAB.NGAWI', NULL),
                                                                                ('APRIZAL MAHENDRA', 'SANGGAR SENI "NEW ARSHIKA MUSIC"', 'DSN. KARANGPOH 1, RT 06/RW 06, DS. SIDOREJO, KEC. KARANGJATI, KAB. NGAWI', NULL),
                                                                                ('SATRIA PAMBUDI AIRLANGGA', 'SANGGAR SENI "AIRLANGGA PRODUCTION"', 'CABEAN, RT 03/RW 01, DS. KARANGTENGAH PRANDON, KEC. NGAWI, KAB. NGAWI', NULL),
                                                                                ('SUGIYO', 'SANGGAR SENI "ORKES MELAYU CAESAR"', 'SELANG, DS. PLOSO LOR, RT/RW : 05/03, KEC. KARANGJATI, KAB. NGAWI', NULL),
                                                                                ('TRI MARSAHID', 'SANGGAR SENI "PANDAWA CAMPURSARI"', 'TELUK, DS. SAMBIREJO, RT/RW : 003/003, KEC. MANTINGAN, KAB. NGAWI', NULL),
                                                                                ('MARIYONO', 'CAMPURSARI" GANESA MUSIC"', 'WONOKERTO, RT/RW:001/004, KARANGBANYU, WIDODAREN, NGAWI', NULL),
                                                                                ('PUGUH WIDAYAT', 'SANGGAR SENI "KHANZA MUSIC"', 'SAMBIROTO II, SAMBIROTO, RT/RW : 002/002, KEC. PADAS, KAB. NGAWI', NULL),
                                                                                ('AJIS SAPUTRA', 'ORKES "OM ZENATA"', 'KEDUNGGLAGAH, DS. SIDOREJO, RT/RW : 003/005, KEC. GENENG, KAB. NGAWI', NULL);