ALTER TABLE organisasi
    ADD COLUMN status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    ADD COLUMN catatan VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;