-- CREATE TABLE IF NOT EXISTS dokumen_pendukung (
--     id BIGSERIAL PRIMARY KEY,
--     form_pengajuan_uuid UUID NOT NULL,
--     url TEXT,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_form_pengajuan_uuid
--         FOREIGN KEY (form_pengajuan_uuid)
--             REFERENCES form_pengajuan (uuid)
--             ON DELETE CASCADE
-- );